language: python
#sudo: required
python:
  - "3.7"
#  - "pypy"
#  - "pypy3"
#matrix:
#  allow_failures:
#    - python: pypy
#    - python: pypy3
before_install:
    - python3 --version
    - pip3 install -U pip
    - pip3 install -U pytest
    - pip3 install codecov
install:
  - "pip3 install -e git+https://github.com/jaullo/pySignatureCR.git@1.0.0#egg=pysignaturecr"
  - pip3 install "setuptools<34"
  - pip3 install "xmlsig"
  - pip3 install "pytz"
  - pip3 install "lxml"
  - pip3 install "datetime"
  - pip3 install "pytest-cov>=1.8.1"
  - pip3 install "lxml>=2.3"
  - pip3 install "pytest"
script:
  - pytest --cov=./
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coveralls; fi